CREATE TABLE [crm].[companies] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [tenant] [nvarchar](255) NOT NULL CONSTRAINT [DF_companies_tenant] DEFAULT ('default'),
    [name] [nvarchar](200) NOT NULL,
    [sector] [nvarchar](100) NULL,
    [size] [int] NOT NULL CONSTRAINT [DEFAULT_company_size] DEFAULT ((1)),
    [linkedin_url] [nvarchar](2048) NULL,
    [website] [nvarchar](2048) NULL,
    [phone_number] [nvarchar](50) NULL,
    [address] [nvarchar](300) NULL,
    [zipcode] [nvarchar](20) NULL,
    [city] [nvarchar](100) NULL,
    [state_abbr] [nvarchar](20) NULL,
    [country] [nvarchar](100) NULL,
    [description] [nvarchar](MAX) NULL,
    [revenue] [nvarchar](50) NULL,
    [tax_identifier] [nvarchar](100) NULL,
    [created_at] [datetime2](0) NOT NULL,
    [sales_id] [int] NULL,
    [logo_src] [nvarchar](2048) NULL,
    [logo_title] [nvarchar](255) NULL,
    [logo_path] [nvarchar](1024) NULL,
    [logo_type] [nvarchar](128) NULL,
    [context_links] [nvarchar](MAX) NULL,
    CONSTRAINT [PK_company] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [CK_company_size] CHECK ([size]=(500) OR [size]=(250) OR [size]=(50) OR [size]=(10) OR [size]=(1)),
    CONSTRAINT [FK_company_tenant] FOREIGN KEY ([tenant]) REFERENCES [crm].[tenants] ([name])
);
