CREATE TABLE [crm].[contacts] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [tenant] [nvarchar](255) NOT NULL CONSTRAINT [DF_contacts_tenant] DEFAULT ('default'),
    [first_name] [nvarchar](100) NOT NULL,
    [last_name] [nvarchar](100) NOT NULL,
    [title] [nvarchar](150) NOT NULL,
    [company_id] [int] NOT NULL,
    [sales_id] [int] NOT NULL,
    [linkedin_url] [nvarchar](2048) NULL,
    [first_seen] [datetime2](0) NULL,
    [last_seen] [datetime2](0) NULL,
    [has_newsletter] [bit] NULL CONSTRAINT [DF_contact_has_newsletter] DEFAULT ((0)),
    [gender] [nvarchar](50) NULL,
    [status] [nvarchar](50) NULL,
    [background] [nvarchar](MAX) NULL,
    [emails_json] [nvarchar](MAX) NULL,
    [phones_json] [nvarchar](MAX) NULL,
    [avatar_src] [nvarchar](2048) NULL,
    [avatar_title] [nvarchar](255) NULL,
    [avatar_path] [nvarchar](1024) NULL,
    [avatar_type] [nvarchar](128) NULL,
    CONSTRAINT [PK_contact] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [CK_contact_emails_json] CHECK (isjson([emails_json])=(1)),
    CONSTRAINT [CK_contact_phones_json] CHECK (isjson([phones_json])=(1)),
    CONSTRAINT [FK_contact_tenant] FOREIGN KEY ([tenant]) REFERENCES [crm].[tenants] ([name])
);
